#ifndef DEFAULTVALUES_H
#define DEFAULTVALUES_H

#define BODY_COLOR_HEX "#c0c0c0"
#define BODY_COLOR_RGB 192, 192, 192
#define SPEECH_COLOR_HEX "#00ff00"
#define SPEECH_COLOR_RGB 0, 255, 0
#define ROOM_NAME_COLOR_HEX "#ffffff"
#define ROOM_NAME_COLOR_RGB 255, 255, 255
#define GAME_MESSAGE_COLOR_HEX "#ffff7f"
#define GAME_MESSAGE_COLOR_RGB 255, 255, 127
#define THINKING_COLOR_HEX "#cd6900"
#define THINKING_COLOR_RGB 205, 115, 0
#define BOOST_COLOR_HEX "#aaff7f"
#define BOOST_COLOR_RGB 170, 255, 127
#define PENALTY_COLOR_HEX "#ff557f"
#define PENALTY_COLOR_RGB 255, 85, 127

#define ROOM_NAME "1_roomName"
#define GAME_MESSAGE "2_gameMessage"
#define SPEECH "3_speech"
#define THINKING "4_thinking"
#define BONUS "5_bonus"
#define PENALTY "6_penalty"

#define DEFAULT_MAIN_FONT "Consolas"
#define DEFAULT_MAIN_FONT_SIZE 12
#define DEFAULT_MAIN_FONT_COLOR "#c8c8c8"
#define DEFAULT_MAIN_BACKGROUND "#000000"

#define DEFAULT_DOCK_FONT "Consolas"
#define DEFAULT_DOCK_FONT_SIZE 11
#define DEFAULT_DOCK_FONT_COLOR "#c8c8c8"
#define DEFAULT_DOCK_BACKGROUND "#000000"

#endif // DEFAULTVALUES_H
