#ifndef GLOBALDEFINES_H
#define GLOBALDEFINES_H

#define GAME_WINDOW_LIMIT 3500

#define MAP_TOP_MARGIN 20

#define WINDOW_SELECT_ALL "All"

#define REGEX_ERROR_COLOR_HEX "#EE3233"

#define RT_COLOR_HEX "#E86850"
#define CT_COLOR_HEX "#66A7C5"

#endif // GLOBALDEFINES_H
