######################################################################
# Automatically generated by qmake (3.1) Sun Oct 16 19:43:52 2022
######################################################################

QT += testlib xml

TEMPLATE = app
TARGET = xmlparserthreadtest
INCLUDEPATH += . .. ../..
include(../xml.pri)

# Input
SOURCES += ../../textutils.cpp \
../../gamedatacontainer.cpp \
../../hyperlinkutils.cpp

HEADERS += ../../textutils.h \
../../gamedatacontainer.h \
../../hyperlinkutils.h


# Test file
SOURCES += xmlparserthreadtest.cpp
