100.times do
  exp = get_exp "climbing"

  echo "*** #{exp.numeric_state} ***"

  if exp.numeric_state >= 33
    echo "*** DONE ***"
    abort
  end

  move "go gate"
  move "west"
  move "west"
  move "south"
  move "south"
  move "west"
  move "west"
  move "south"
  move "west"
  move "west"
  move "west"
  move "west"
  move "west"
  move "west"
  move "go bridge"
  move "west"
  move "west"
  move "west"
  move "west"
  move "go gate"
  move "climb wall"
  move "south"
  move "climb embrasure"
  move "climb wall"
  move "north"
  move "east"
  move "climb break"
  move "climb wall"
  move "climb embrasure"
  move "climb wall"
  move "west"
  move "climb embrasure"
  move "go gate"
  move "east"
  move "east"
  move "east"
  move "east"
  move "east"
  move "east"
  move "east"
  move "east"
  move "south"
  move "south"
  move "south"
  move "south"
  move "south"
  move "east"
  move "east"
  move "southeast"
  move "east"
  move "east"
  move "east"
  move "east"
  move "go gate"
  move "climb wall"
  move "north"
  move "climb break"
  move "climb wall"
  move "climb embrasure"
  move "climb wall"
  move "south"
  move "climb embrasure"
  move "go bushes"
  move "north"
  move "northeast"
  move "north"
  move "north"
  move "up"
  move "north"
  move "north"
end