echo "- Subtlety:"
echo ""
echo "<div style=\"white-space: pre;\" class=\"thinking\"> Darken (Augmentation) {8/2} - <span class=\"room-name\">Stealth boost.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">     |-- Dampen (Augmentation) {12/3} - <span class=\"room-name\">Stealth hinderance reduction.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">     |     |-- Shadowstep (Utility) {16/4} - <span class=\"room-name\">Quick engagement through the shadows.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">     |     |-- Sensing (Utility) {16/4} - <span class=\"room-name\">See different directions.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">     |</div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">     |-- Strike (Augmentation) {12/3} - <span class=\"room-name\">Backstab and melee weapon boost.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">     |</div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">     |-- Silence (Utility) {12/3} - <span class=\"room-name\">Pulsing Invisibility.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">     |     |-- Vanish <span style=\"color: #BF360C;\">[S]</span> (Utility) {30} - <span class=\"room-name\">Disengage into innvisibility.</span></div>"
echo ""
echo "- Finesse:"
echo ""
echo "<div style=\"white-space: pre;\" class=\"thinking\"> Hasten (Utility) {8/2} - <span class=\"room-name\">Chance for RT reduction on attacks, RT to remove armor in combat, as well as reducing the time it takes to flee</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      |-- Safe (Augmentation) {12/3} - <span class=\"room-name\">Locksmithing boost.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      |</div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      |-- Avoidance (Augmentation) {12/3} - <span class=\"room-name\">Reflex boost.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      |     |-- Flight (Augmentation) {16/4} - <span class=\"room-name\">Athletics and pulsing balance boost.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      |           |-- Elusion (Augmentation) {16/4} - <span class=\"room-name\">Evasion and brawling boost.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      |           |-- Liberation (Utility) {16/4} - <span class=\"room-name\">Pulsing web/immobilize breaker.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      |</div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      |-- Plunder (Augmentation) {16/4} - <span class=\"room-name\">Discipline and thievery boost.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      |     |-- Guile (Debilitation) {20/5} - <span class=\"room-name\">AOE pulsing evasion debuff (engaged) Charm vs Will.</span></div>"
echo ""
echo "- Potence:"
echo ""
echo "<div style=\"white-space: pre;\" class=\"thinking\"> Focus (Augmentation) {8/2} - <span class=\"room-name\">Agility boost.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      |-- Sight (Augmentation) {12/3} - <span class=\"room-name\">Perception boost, see in the dark.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      |</div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      |-- Prowess (Debilitation) {16/4} - <span class=\"room-name\">AOE pulsing reflex and tactics debuff (engaged) Fear vs Will when hidden, Power vs Will otherwise.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      |     |-- Steady (Augmentation) {16/4} - <span class=\"room-name\">Bow/XBow boost.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      |     |-- Eliminate <span style=\"color: #BF360C;\">[S]</span> (Debilitation) {35} - <span class=\"room-name\">Brief (like 5 seconds) no shield and no armor debuff.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      |</div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      |-- Calm <span style=\"color: #BF360C;\">[S]</span> (Utility) {25} - <span class=\"thinking\">Self dispel.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      |     |-- Serenity (Utility) {16/4} - <span class=\"room-name\">SvS barrier vs Will.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      |           |-- Sagacity (Utility) {20/5} - <span class=\"room-name\">Physical damage ward.</span></div>"
echo ""
echo " - Combination Khri:"
echo ""
echo "<div style=\"white-space: pre;\" class=\"thinking\">      Secure - Focus, Safe and Sight - <span class=\"room-name\">Additional chance not to blow a box.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      Speed - Avoidance, Plunder and Flight - <span class=\"room-name\">chance to return thrown weapons back to attacker</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      Spar - Strike, Steady and Elusion - <span class=\"room-name\">Thrown weapons boost.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      Skulk - Darken, Dampen and Shadowstep - <span class=\"room-name\">0 second sneak in urban areas, +nolocate.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      Prescience - Sensing, Serenity and Sagacity - <span class=\"room-name\">Passive spot, additional guard avoidance/justice thinking.</span></div>"
echo "<div style=\"white-space: pre;\" class=\"thinking\">      Cunning - Hasten, Guile and Liberation - <span class=\"room-name\">Charisma/Tactics boost</span></div>"
