echo "- Subtlety:"
echo ""
echo "<div style=\"white-space: pre;color: black;\"> Darken (Augmentation) {8/2} - <span style=\"color: #787878;\">Stealth boost.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">     |-- Dampen (Augmentation) {12/3} - <span style=\"color: #787878;\">Stealth hinderance reduction.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">     |     |-- Shadowstep (Utility) {16/4} - <span style=\"color: #787878;\">Quick engagement through the shadows.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">     |     |-- Sensing (Utility) {16/4} - <span style=\"color: #787878;\">See different directions.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">     |</div>"
echo "<div style=\"white-space: pre;color: black;\">     |-- Strike (Augmentation) {12/3} - <span style=\"color: #787878;\">Backstab and melee weapon boost.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">     |</div>"
echo "<div style=\"white-space: pre;color: black;\">     |-- Silence (Utility) {12/3} - <span style=\"color: #787878;\">Pulsing Invisibility.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">     |     |-- Vanish <span style=\"color: #BF360C;\">[S]</span> (Utility) {30} - <span style=\"color: #787878;\">Disengage into innvisibility.</span></div>"
echo ""
echo "- Finesse:"
echo ""
echo "<div style=\"white-space: pre;color: black;\"> Hasten (Utility) {8/2} - <span style=\"color: #787878;\">Chance for RT reduction on attacks, RT to remove armor in combat, as well as reducing the time it takes to flee</span></div>"
echo "<div style=\"white-space: pre;color: black;\">      |-- Safe (Augmentation) {12/3} - <span style=\"color: #787878;\">Locksmithing boost.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">      |</div>"
echo "<div style=\"white-space: pre;color: black;\">      |-- Avoidance (Augmentation) {12/3} - <span style=\"color: #787878;\">Reflex boost.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">      |     |-- Flight (Augmentation) {16/4} - <span style=\"color: #787878;\">Athletics and pulsing balance boost.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">      |           |-- Elusion (Augmentation) {16/4} - <span style=\"color: #787878;\">Evasion and brawling boost.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">      |           |-- Liberation (Utility) {16/4} - <span style=\"color: #787878;\">Pulsing web/immobilize breaker.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">      |</div>"
echo "<div style=\"white-space: pre;color: black;\">      |-- Plunder (Augmentation) {16/4} - <span style=\"color: #787878;\">Discipline and thievery boost.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">      |     |-- Guile (Debilitation) {20/5} - <span style=\"color: #787878;\">AOE pulsing evasion debuff (engaged) Charm vs Will.</span></div>"
echo ""
echo "- Potence:"
echo ""
echo "<div style=\"white-space: pre;color: black;\"> Focus (Augmentation) {8/2} - <span style=\"color: #787878;\">Agility boost.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">      |-- Sight (Augmentation) {12/3} - <span style=\"color: #787878;\">Perception boost, see in the dark.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">      |</div>"
echo "<div style=\"white-space: pre;color: black;\">      |-- Prowess (Debilitation) {16/4} - <span style=\"color: #787878;\">AOE pulsing reflex and tactics debuff (engaged) Fear vs Will when hidden, Power vs Will otherwise.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">      |     |-- Steady (Augmentation) {16/4} - <span style=\"color: #787878;\">Bow/XBow boost.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">      |     |-- Eliminate <span style=\"color: #BF360C;\">[S]</span> (Debilitation) {35} - <span style=\"color: #787878;\">Brief (like 5 seconds) no shield and no armor debuff.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">      |</div>"
echo "<div style=\"white-space: pre;color: black;\">      |-- Calm <span style=\"color: #BF360C;\">[S]</span> (Utility) {25} - <span style=\"color: #787878;\">Self dispel.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">      |     |-- Serenity (Utility) {16/4} - <span style=\"color: #787878;\">SvS barrier vs Will.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">      |           |-- Sagacity (Utility) {20/5} - <span style=\"color: #787878;\">Physical damage ward.</span></div>"
echo ""
echo " - Combination Khri:"
echo ""
echo "<div style=\"white-space: pre;color: black;\">      Secure - Focus, Safe and Sight - <span style=\"color: #787878;\">Additional chance not to blow a box.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">      Speed - Avoidance, Plunder and Flight - <span style=\"color: #787878;\">chance to return thrown weapons back to attacker</span></div>"
echo "<div style=\"white-space: pre;color: black;\">      Spar - Strike, Steady and Elusion - <span style=\"color: #787878;\">Thrown weapons boost.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">      Skulk - Darken, Dampen and Shadowstep - <span style=\"color: #787878;\">0 second sneak in urban areas, +nolocate.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">      Prescience - Sensing, Serenity and Sagacity - <span style=\"color: #787878;\">Passive spot, additional guard avoidance/justice bonus.</span></div>"
echo "<div style=\"white-space: pre;color: black;\">      Cunning - Hasten, Guile and Liberation - <span style=\"color: #787878;\">Charisma/Tactics boost</span></div>"
