echo "***"
echo Status::standing
echo Status::kneeling
echo Status::sitting
echo Status::prone
echo Status::stunned
echo Status::bleeding
echo Status::hidden
echo Status::joined
echo Status::webbed
echo Status::dead
echo "***"
echo Room::title
echo Room::description
echo Room::objects
echo Room::players
echo Room::exits
echo Room::count_objects "hog"
echo "***"
echo Exp::state("climb")
echo Exp::rank("climb")
echo "***"
echo Inventory::list
echo "***"
echo Container::list
echo "***"
echo Wield::right
echo Wield::right_noun
echo Wield::left
echo Wield::left_noun
echo "***"
echo Vitals::health
echo Vitals::concentration
echo Vitals::spirit
echo Vitals::fatigue
echo "***"