move "go path"
move "ne"
move "nw"
move "n"
move "ne"
move "w"
move "w"
move "go crevice"
move "go woodlands"
move "ne"
move "ne"
move "n"
move "ne"
move "n"
move "n"
move "climb fallen log"
move "climb embankment"
move "sw"
move "s"
move "down"
move "climb stone wall"
move "climb narrow ledge"
move "climb craggy niche"
move "climb branch"